# Generated by Django 5.1.14 on 2026-02-13 01:18

import bots.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0075_alter_botmediarequest_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiochunk',
            name='audio_blob_remote_file',
            field=models.FileField(blank=True, null=True, storage=bots.storage.StorageAlias('audio_chunks'), upload_to=''),
        ),
        migrations.AddField(
            model_name='audiochunk',
            name='blob_upload_failure_data',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='audiochunk',
            name='is_blob_stored_remotely',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
