# Generated by Django 5.1.14 on 2026-04-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0079_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediablob',
            name='content_type',
            field=models.CharField(choices=[('audio/mp3', 'MP3 Audio'), ('image/png', 'PNG Image'), ('image/jpeg', 'JPEG Image')], max_length=255),
        ),
    ]
